### ISSUE TITLE
Integration into W4M server

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/isa-extractor#18]
- [x] Use planemo lint on all tools.
- [x] Write a test for isa2mzdata.
- [x] Write a test for isa2mzml.
- [x] Write a test for isa2mzxml.
- [x] Write a test for isa2netcdf.
- [x] Write a test for isa2nmrml.
- [x] Publish onto test toolshed.
- [x] Install and test on test instance.
- [x] Publish onto main toolshed.
- [x] Install and test on main instance.

**Comment by pkrog** [comment]
Hi @lecorguille , this tool is ready to be installed. You will find it on the test toolshed:
<https://testtoolshed.g2.bx.psu.edu/view/prog/isaextractor/deb654d58b15>
and the main tool shed:
<https://toolshed.g2.bx.psu.edu/view/prog/isaextractor/975585306dc4>.

cc: @sneumann

**Comment by lecorguille** [comment]
Done

@pkrog Can you imagine pushing this tools in https://github.com/workflow4metabolomics/tools-metabolomics ?

**Comment by pkrog** [comment]
> Done
> 
> @pkrog Can you imagine pushing this tools in https://github.com/workflow4metabolomics/tools-metabolomics ?

Why not. However it uses a bash script. Does that mean I will have to create a bioconda package for that script?

**Comment by lecorguille** [comment]
> Does that mean I will have to create a bioconda package for that script?

My wish is indeed to reduce the number of code within the wrappers (it will be a long process ... at least with mine). Because, for me an analysis should get the same result within and outside Galaxy. 

So, it's up to you if you consider that this script can be useful outside Galaxy. But it's not mandatory to be in [tools-metabolomics](https://github.com/workflow4metabolomics/tools-metabolomics )
